# Generated by Django 3.2.9 on 2021-11-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='短链')),
                ('url', models.CharField(max_length=255, verbose_name='目标url')),
            ],
        ),
    ]
